"""empty message

Revision ID: 17fd5979ba9f
Revises: 8d9af428a331
Create Date: 2025-07-04 22:05:39.415381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fd5979ba9f'
down_revision = '8d9af428a331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_orders_order_id', ['order_id'])  # <- constraint name added

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_orders_order_id', type_='unique')  # <- match the name
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
