"""empty message

Revision ID: 5a005ebd96ce
Revises: bab6243982bd
Create Date: 2025-07-28 14:27:01.612308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a005ebd96ce'
down_revision = 'bab6243982bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seen_by_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('seen_by_admin')

    # ### end Alembic commands ###
