"""empty message

Revision ID: 62998925cf7f
Revises: 0cba83c56e5f
Create Date: 2025-10-07 08:24:10.718974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62998925cf7f'
down_revision = '0cba83c56e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sign_up_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sign_up_approved')

    # ### end Alembic commands ###
