"""empty message

Revision ID: 77c91a35223d
Revises: 958ecd9fa5fa
Create Date: 2025-07-20 10:55:52.568924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77c91a35223d'
down_revision = '958ecd9fa5fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('telegram_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_constraint('fk_orders_telegram_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_orders_telegram_id', 'telegram_ids', ['telegram_id'], ['id'])
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_telegram_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_orders_telegram_id', 'telegram_ids', ['telegram_id'], ['telegram_id'])
        batch_op.alter_column('telegram_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
