"""empty message

Revision ID: 958ecd9fa5fa
Revises: fbb5ac653827
Create Date: 2025-07-20 10:36:19.661733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958ecd9fa5fa'
down_revision = 'fbb5ac653827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_orders')  # Removed because table may not exist
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_orders_telegram_id', 'telegram_ids', ['telegram_id'], ['telegram_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_telegram_id', type_='foreignkey')
        batch_op.drop_column('telegram_id')

    op.create_table('_alembic_tmp_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_type', sa.VARCHAR(length=4), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('thai_bank_account_id', sa.INTEGER(), nullable=True),
    sa.Column('myanmar_bank_account_id', sa.INTEGER(), nullable=True),
    sa.Column('receipt', sa.VARCHAR(length=255), nullable=True),
    sa.Column('confirm_receipt', sa.VARCHAR(length=255), nullable=True),
    sa.Column('qr', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.VARCHAR(length=8), nullable=True),
    sa.Column('user_bank', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('order_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('telegram_id', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['myanmar_bank_account_id'], ['myanmar_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['telegram_id'], ['telegram_ids.telegram_id'], name=op.f('fk_orders_telegram_id')),
    sa.ForeignKeyConstraint(['thai_bank_account_id'], ['thai_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name=op.f('uq_orders_order_id'))
    )
    # ### end Alembic commands ###
