"""empty message

Revision ID: 9ec1623b0b6c
Revises: 1e7645e58c52
Create Date: 2025-07-19 17:28:33.959390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec1623b0b6c'
down_revision = '1e7645e58c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_backend', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('seen_by_user', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('seen_by_user')
        batch_op.drop_column('from_backend')

    # ### end Alembic commands ###
