"""empty message

Revision ID: a09740361111
Revises: f03339d4ef4a
Create Date: 2025-07-19 16:57:39.250699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09740361111'
down_revision = 'f03339d4ef4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_ids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_ids', schema=None) as batch_op:
        batch_op.drop_column('chat_id')

    # ### end Alembic commands ###
