"""empty message

Revision ID: a4d00931adaa
Revises: 17fd5979ba9f
Create Date: 2025-07-16 20:50:14.296398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError

# revision identifiers, used by Alembic.
revision = 'a4d00931adaa'
down_revision = '17fd5979ba9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('telegram_ids',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('telegram_id', sa.String(length=255), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('telegram_id')
        )
    except OperationalError:
        pass

    try:
        op.create_table('messages',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('content', sa.String(length=1024), nullable=False),
            sa.Column('chosen_option', sa.String(length=1024), nullable=False),
            sa.Column('image', sa.String(length=255), nullable=True),
            sa.Column('telegram_id', sa.String(length=255), nullable=False),
            sa.ForeignKeyConstraint(['telegram_id'], ['telegram_ids.telegram_id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    except OperationalError:
        pass

    from sqlalchemy.engine import reflection
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)

    try:
        with op.batch_alter_table('myanmar_bank_accounts', schema=None) as batch_op:
            fks = [fk['name'] for fk in inspector.get_foreign_keys('myanmar_bank_accounts')]
            if 'myanmar_bank_accounts_user_id_fkey' in fks:
                batch_op.drop_constraint('myanmar_bank_accounts_user_id_fkey', type_='foreignkey')
            cols = [col['name'] for col in inspector.get_columns('myanmar_bank_accounts')]
            if 'user_id' in cols:
                batch_op.drop_column('user_id')
    except OperationalError:
        pass

    try:
        with op.batch_alter_table('thai_bank_accounts', schema=None) as batch_op:
            fks = [fk['name'] for fk in inspector.get_foreign_keys('thai_bank_accounts')]
            if 'thai_bank_accounts_user_id_fkey' in fks:
                batch_op.drop_constraint('thai_bank_accounts_user_id_fkey', type_='foreignkey')
            cols = [col['name'] for col in inspector.get_columns('thai_bank_accounts')]
            if 'user_id' in cols:
                batch_op.drop_column('user_id')
    except OperationalError:
        pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('thai_bank_accounts', schema=None) as batch_op:
            batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
            batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
    except OperationalError:
        pass

    try:
        with op.batch_alter_table('myanmar_bank_accounts', schema=None) as batch_op:
            batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
            batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
    except OperationalError:
        pass

    try:
        op.drop_table('messages')
    except OperationalError:
        pass

    try:
        op.drop_table('telegram_ids')
    except OperationalError:
        pass
    # ### end Alembic commands ###
