"""empty message

Revision ID: bab6243982bd
Revises: 
Create Date: 2025-07-21 15:14:29.381162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab6243982bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=255), nullable=True),
    sa.Column('telegram_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1024), nullable=False),
    sa.Column('chosen_option', sa.String(length=1024), nullable=True),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('from_bot', sa.Boolean(), nullable=True),
    sa.Column('from_backend', sa.Boolean(), nullable=True),
    sa.Column('seen_by_user', sa.Boolean(), nullable=True),
    sa.Column('buttons', sa.String(length=1024), nullable=True),
    sa.Column('telegram_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['telegram_id'], ['telegram_ids.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('myanmar_bank_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('myanmar_bank_accounts_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'telegram_ids', ['telegram_id'], ['id'])

    with op.batch_alter_table('thai_bank_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('thai_bank_accounts_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thai_bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('thai_bank_accounts_user_id_fkey'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('telegram_id')

    with op.batch_alter_table('myanmar_bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('myanmar_bank_accounts_user_id_fkey'), 'users', ['user_id'], ['id'])

    op.drop_table('messages')
    op.drop_table('telegram_ids')
    # ### end Alembic commands ###
