"""empty message

Revision ID: bc186ff40f00
Revises: 
Create Date: 2025-07-04 05:38:27.672407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc186ff40f00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_feature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('on', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buy', sa.Float(), nullable=False),
    sa.Column('sell', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('on', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('myanmar_bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('on', sa.Boolean(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('qr_image', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thai_bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('on', sa.Boolean(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('qr_image', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.Enum('buy', 'sell', name='order_type'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thai_bank_account_id', sa.Integer(), nullable=True),
    sa.Column('myanmar_bank_account_id', sa.Integer(), nullable=True),
    sa.Column('receipt', sa.String(length=255), nullable=True),
    sa.Column('confirm_receipt', sa.String(length=255), nullable=True),
    sa.Column('qr', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'declined', name='order_status'), nullable=True),
    sa.ForeignKeyConstraint(['myanmar_bank_account_id'], ['myanmar_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['thai_bank_account_id'], ['thai_bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('thai_bank_accounts')
    op.drop_table('myanmar_bank_accounts')
    op.drop_table('users')
    op.drop_table('otp')
    op.drop_table('maintenance_mode')
    op.drop_table('exchange_rates')
    op.drop_table('auth_feature')
    # ### end Alembic commands ###
