"""empty message

Revision ID: f03339d4ef4a
Revises: a4d00931adaa
Create Date: 2025-07-18 09:37:18.091782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03339d4ef4a'
down_revision = 'a4d00931adaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_bot', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('buttons', sa.String(length=1024), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('buttons')
        batch_op.drop_column('from_bot')

    # ### end Alembic commands ###
