"""empty message

Revision ID: f336e8fd9e41
Revises: 2cba63d51988
Create Date: 2025-10-25 16:11:05.159218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f336e8fd9e41'
down_revision = '2cba63d51988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('myanmar_bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_account', sa.String(length=255), nullable=True))

    with op.batch_alter_table('thai_bank_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_account', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thai_bank_accounts', schema=None) as batch_op:
        batch_op.drop_column('staff_account')

    with op.batch_alter_table('myanmar_bank_accounts', schema=None) as batch_op:
        batch_op.drop_column('staff_account')

    # ### end Alembic commands ###
